name: Pause

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      # required_job_name:
      #   required: true
      #   type: string
      

jobs:
  manual-action:
    runs-on: ubuntu-latest
    # needs: ${{ inputs.required_job_name }}
    if: success()
    environment: manual-action
    steps:
    - name: Pause for manual approval
      run: |
        echo "The deployment is paused. \
        Please approve it in the GitHub Actions tab for \
        service: ${{ inputs.service_name }}, commit: ${GITHUB_BASE_REF}."