name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
 
env:
  SERVICE_NAME: my-service

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with unittest
      run: |
        pwd
        ls -la
        ls -la tests
        python -m unittest discover tests
        # echo "Well I would run tests here but they don't work for service: ${SERVICE_NAME}, commit: ${GITHUB_BASE_REF}"

  pause:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/manual_trigger.yml
    needs: test
    with:
      service_name: $SERVICE_NAME

  build:
    runs-on: ubuntu-latest
    needs: pause
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Short Commit SHA
      run: |
        echo "=============================="
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "short_sha: ${{env.sha_short}}"
        echo "=============================="


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: > 
          ${{ secrets.DOCKER_USERNAME }}/my_python_project:${{ env.sha_short }},
          ${{ secrets.DOCKER_USERNAME }}/my_python_project:latest

  