name: Python package

on: [push]

jobs:
  test:
    if: ${{ github.event_name }} == workflow_dispatch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with unittest
      run: |
        pwd
        ls -la
        ls -la tests
        # python -m unittest discover tests
        REPO=${{GITHUB_REPOSITORY}}
        echo "Well I would run tests here but they don't work for repo ${REPO##*/}, commit: ${{GITHUB_SHA}}"

  build:
    runs-on: ubuntu-latest
    environment: manual-action

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my_python_project:latest